require: standard

inherit_gem:
  standard: config/base.yml

inherit_from:
  - .rubocop_rails.yml
  - .rubocop_rspec.yml

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb
    - vendor/bundle/**/*

