---
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= [5, *ENV.values_at("RAILS_MAX_THREADS", "SIDEKIQ_CONCURRENCY")].map(&:to_i).max %>

development:
  <<: *default
  database: planus_development

test:
  <<: *default
  database: planus_test

production:
  <<: *default
  url: planus_production

